// src/app/layout.tsx
import Header from "./components/Header";
import Footer from "./components/Footer";// Assurez-vous que le chemin est correct
import type { Metadata } from "next";
import localFont from "next/font/local";
import AppWalletProvider from "./components/AppWalletProvider";
import "./globals.css";

const geistSans = localFont({
	src: "./fonts/GeistVF.woff",
	variable: "--font-geist-sans",
	weight: "100 900",
});
const geistMono = localFont({
	src: "./fonts/GeistMonoVF.woff",
	variable: "--font-geist-mono",
	weight: "100 900",
});

export const metadata: Metadata = {
	title: "Trusted",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<AppWalletProvider>
					<Header />
					<main style={{ marginTop: "80px" }}>
						{children}
					</main>
				</AppWalletProvider>
				<Footer />
			</body>
		</html>
	);
}
